name: Notarize repository with cas and vcn

on:
  workflow_call:
    secrets:
      vcn-api-key:
        description: 'The signer key for vcn.'
        required: true
      vcn-host:
        description: 'The host for vcn.'
        required: true

jobs:
  notarize-repository:
    name: Notarize repository
    runs-on: [self-hosted, linux]
    env:
      VCN_LC_HOST: ${{ secrets.vcn-host }}
      VCN_LC_API_KEY: ${{ secrets.vcn-api-key }}
    steps:
      - name: 'Cleanup build folder'
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download vcn
        run: |
          curl -s -o vcn -L https://vcn-releases.codenotary.com/vcn-latest-linux-amd64-static
          chmod +x vcn

      - name: Notarize git repository with vcn
        run: ./vcn n git://$GITHUB_WORKSPACE --bom

      - name: Notarize git repository directory with vcn
        run: ./vcn n dir://$GITHUB_WORKSPACE
